[migration]
path = "./migration"

[database]
host = "192.116.0.10"
user = "meu_usuario"
pass = "1234abc?"
db = "aprendagolang"

[deploy]
clients = [123, 7782, 7612]

[servers]

  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"