# BuildStage

FROM golang:1.21.10-alpine as BuildStage

WORKDIR /app

COPY *.go .
COPY go.* .

RUN go mod tidy

RUN GOOS=linux go build -o app server.go

# Deploy Stage

from alpine:latest

WORKDIR /app

COPY --from=BuildStage /app/app ./

EXPOSE 8080

ENTRYPOINT ["./app"]